name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.1

            # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'bun'

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run Format Check
        run: bun run format
